#+TITLE: 2018 Summer Internship Boarding Document
#+AUTHOR: VLEAD
#+DATE: [2018-04-18 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Welcome

  Welcome to Virtual Labs - 2018 Summer Internship Program @ IIITH !!!

  We are delighted you are joining us as a new intern. This program has been
  developed for students to gain practical training and hands-on, real world
  experience that will help them meet their educational goals and prepare them
  for a professional career.  The VLEAD team is here to support your
  transition, so can call on any of us to assist you.

* Instructions to Interns
** Prerequisites
  1. Setup your machine with [[https://www.vagrantup.com/intro/getting-started/index.html][Vagrant]] for virtualization.
  2. Create =VLEAD DEV= vagrant box from this [[http://files.vlabs.ac.in/downloads/vagrant-boxes/vlead-dev.box][box]].
  3. Install and configure emacs using this [[https://gitlab.com/vxcg/pub/emacs/emacs][repo]].  Use the
     makefile to configure.
  4. Get comfortable with [[http://orgmode.org/][emacs]] editor and [[http://orgmode.org/][org-mode]].
  5. Read about [[https://martinfowler.com/articles/microservices.html][microservices]]. 

** Access Card
   An RFID card will be issued to you on Day 1 of the internship
   program by Ravi Kiran, Program Officer, Virtual Labs. This should
   be swiped everyday at B6-205, VLEAD Room (when you come in and
   leave) for logging attendance.

** Working Hours
   Your working hours for the internship period is from 9:00 A.M to 6:00P.M
   (Monday - Friday).

** Leave Policy
   You are not allowed to take any leave during the internship period.
** Work Logs
   1. Follow the =instructions.org= to create a work-logs directory.

   2. You have to get your work-log approved from your mentor on a weekly
      basis. You will also need to submit your approved work-log to
      ravi.kiran@vlabs.ac.in . Your stipend will be released against this
      submission only.
      
** Presentations
  1. All Wednesday & Friday afternoons will be reserved for a short presentation (5-10
     mins) by the interns on their project and progress.

  2. You will need to make a mid-internship presentation at the end of the 4th
     week of internship - week of 11th June to 15th June 2018.

  3. A final presentation (with links to relevant documents) will need to be
     made during the week of 9th July to 13th July 2018 against which the
     internship certificate will be issued.

** IRC Channel
  Please login to IRC channel #vlead on freenode.  Hexchat is an IRC client
  that is used at VLEAD.  =apt-get install hexchat= should allow you to install
  the client on Ubuntu.  Add this program to you startup script to ensure this
  program is up whenever the computer is rebooted. 
